# Generated by Django 2.2.7 on 2019-12-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bordapp', '0002_auto_20191229_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmodel',
            name='images',
            field=models.ImageField(upload_to=''),
        ),
    ]
