# Generated by Django 3.0 on 2020-01-21 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_personteam_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_from', to='practice.Friends')),
                ('_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_to', to='practice.Friends')),
            ],
        ),
    ]
