# Generated by Django 3.0 on 2020-01-21 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_auto_20200121_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='_from',
        ),
        migrations.RemoveField(
            model_name='message',
            name='_to',
        ),
        migrations.AddField(
            model_name='message',
            name='froma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='froma', to='practice.Friends'),
        ),
        migrations.AddField(
            model_name='message',
            name='toa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='toa', to='practice.Friends'),
        ),
    ]
